language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree

install: 
  - wget https://www.tracelytics.com/install_tracelytics.sh
  - sudo sh ./install_tracelytics.sh f51e2a43-0ee5-4851-8a54-825773b3218e

before_script:
  - bundle exec rake compile

services: 
  - mongodb
  - memcached
  - cassandra

